// Auto-generated by scripts/generate-media.js
export const media = {
  heroPoster: '/images/dummy10.png',
  about: {
    main: '/images/dummy1.jpg',
    secondary: '/images/dummy12.jpg',
  },
  programs: ['/images/dummy13.jpg', '/images/dummy14.jpg', '/images/dummy15.jpg', '/images/dummy16.jpg'],
  trainers: ['/images/dummy17.jpg', '/images/dummy18.jpg', '/images/dummy19.jpg', '/images/dummy2.jpg'],
  testimonials: ['/images/dummy20.jpg', '/images/dummy21.jpg', '/images/dummy3.jpg', '/images/dummy4.jpg', '/images/dummy5.jpg'],
  blog: ['/images/dummy6.jpg', '/images/dummy7.jpg', '/images/dummy8.jpg'],
} as const;
