// Generates src/config/media.ts from files in public/images
const fs = require('fs');
const path = require('path');

const imagesDir = path.join(__dirname, '..', 'public', 'images');
const outFile = path.join(__dirname, '..', 'src', 'config', 'media.ts');

function main() {
  if (!fs.existsSync(imagesDir)) {
    console.error('Images directory not found:', imagesDir);
    process.exit(1);
  }
  const files = fs.readdirSync(imagesDir).filter((f) => /\.(png|jpg|jpeg|webp|avif)$/i.test(f));
  if (files.length === 0) {
    console.error('No image files found in', imagesDir);
  }
  // Sort for stable selection
  files.sort((a, b) => a.localeCompare(b));

  // Helper to make absolute public path
  const pub = (f) => `/images/${f}`;

  // Pick hero poster (prefer png/webp)
  const heroPoster = files.find((f) => /poster|hero/i.test(f)) || files.find((f) => /\.(png|webp|avif)$/i.test(f)) || files[0] || '';

  // Simple buckets by index if names aren't semantic
  const jpgs = files.filter((f) => /\.(jpg|jpeg|webp|avif)$/i.test(f));

  const aboutMain = jpgs[0] || files[0] || '';
  const aboutSecondary = jpgs[1] || files[1] || '';

  const programs = [jpgs[2], jpgs[3], jpgs[4], jpgs[5]].filter(Boolean);
  const trainers = [jpgs[6], jpgs[7], jpgs[8], jpgs[9]].filter(Boolean);
  const testimonials = [jpgs[10], jpgs[11], jpgs[12], jpgs[13], jpgs[14]].filter(Boolean);
  const blog = [jpgs[15], jpgs[16], jpgs[17]].filter(Boolean);

  const content = `// Auto-generated by scripts/generate-media.js\nexport const media = {\n  heroPoster: '${pub(heroPoster)}',\n  about: {\n    main: '${pub(aboutMain)}',\n    secondary: '${pub(aboutSecondary)}',\n  },\n  programs: [${programs.map((f) => `'${pub(f)}'`).join(', ')}],\n  trainers: [${trainers.map((f) => `'${pub(f)}'`).join(', ')}],\n  testimonials: [${testimonials.map((f) => `'${pub(f)}'`).join(', ')}],\n  blog: [${blog.map((f) => `'${pub(f)}'`).join(', ')}],\n} as const;\n`;

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, content, 'utf8');
  console.log('Wrote media config to', outFile);
}

main();
